"""make created_by nullable in movies

Revision ID: cc79ec0b78bd
Revises: add_roles_description_and_picks_creator
Create Date: 2025-12-08 18:12:11.859362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc79ec0b78bd'
down_revision: Union[str, Sequence[str], None] = 'add_roles_description_and_picks_creator'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
